sngular/scs-multiapi-plugin

- pom.xml
- styles/Corunet_Style.xml
> #33 Add styles file

- pom.xml
- src/main/java/net/coru/api/generator/plugin/OpenapiMultiFileMojo.java
- src/test/java/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testClientPackageWebClientApiGeneration/api-test.yml
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testClientPackageWebClientApiGeneration/assets/TestAuth.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testClientPackageWebClientApiGeneration/assets/TestClient.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testClientPackageWebClientApiGeneration/assets/TestHttpBasicAuth.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testClientPackageWebClientApiGeneration/pom.xml
> #28 Add auth package

- pom.xml
- src/main/java/net/coru/api/generator/plugin/openapi/utils/OpenApiUtil.java
> Fix wrong get method mixing http operations

- pom.xml
- src/main/resources/templates/openapi/templateSchema.ftlh
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiClientGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiClientGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiClientGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ApiTestInfoDTO.java
> #32 Add builder for model entities when lombok is not used

- pom.xml
- src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperContentUtil.java
- src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperPathUtil.java
- src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperUtil.java
- src/main/java/net/coru/api/generator/plugin/openapi/utils/OpenApiUtil.java
- src/main/resources/templates/openapi/templateSchema.ftlh
- src/main/resources/templates/openapi/templateSchemaWithLombok.ftlh
- src/test/java/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/api-test.yml
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/assets/InlineResponse200DTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/assets/MessageDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/assets/TestApi.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/pom.xml
> #26 Fixed Schema Generation

- README.md
- pom.xml
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ApiTestInfoDTO.java
> #53 Fix failing test

- README.md
- pom.xml
- src/main/java/net/coru/api/generator/plugin/OpenapiMultiFileMojo.java
- src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperPathUtil.java
- src/main/java/net/coru/api/generator/plugin/openapi/utils/OpenApiUtil.java
- src/test/java/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/assets/InlineResponse200CreateGameDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/assets/TestApi.java
> 31 scs multiapi plugin openapi add overwriting model entities parameter

- README.md
- pom.xml
- src/main/resources/templates/openapi/templateSchema.ftlh
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ApiTestInfoDTO.java
> #56 Add import for CollectionUtils

- README.md
- pom.xml
- src/main/java/net/coru/api/generator/plugin/OpenAsyncMojo.java
- src/main/java/net/coru/api/generator/plugin/OpenapiMultiFileMojo.java
- src/main/java/net/coru/api/generator/plugin/openapi/template/TemplateFactory.java
- src/main/java/net/coru/api/generator/plugin/openapi/utils/OpenApiUtil.java
- styles/OSS_style_idea.xml
> Fix style sheet

- README.md
- pom.xml
- src/main/java/net/coru/api/generator/plugin/openapi/model/SchemaFieldObject.java
- src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperContentUtil.java
- src/main/resources/templates/openapi/templateSchema.ftlh
- src/main/resources/templates/openapi/templateSchemaWithLombok.ftlh
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiClientGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiClientGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiClientGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathParameterGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/assets/InlineResponse200CreateGameDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testMultipleRefGeneration/assets/MessageDTO.java
> Added support for Required Fields

- README.md
- pom.xml
- src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperContentUtil.java
- src/main/resources/templates/openapi/template.ftlh
- src/main/resources/templates/openapi/templateCallRestClient.ftlh
- src/main/resources/templates/openapi/templateCallWebClient.ftlh
- src/main/resources/templates/openapi/templateReactive.ftlh
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathWithBarsGeneration/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathWithBarsGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiPathWithBarsGeneration/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiReactiveGeneration/assets/TestApi.java
> Added the possibility of summary as optional

- README.md
- pom.xml
- src/main/java/net/coru/api/generator/plugin/OpenAsyncMojo.java
- src/main/java/net/coru/api/generator/plugin/OpenapiMultiFileMojo.java
- src/main/java/net/coru/api/generator/plugin/PluginConstants.java
- src/main/java/net/coru/api/generator/plugin/asyncapi/exception/AsyncApiGeneratedSourceFolderException.java
- src/main/java/net/coru/api/generator/plugin/exception/GeneratedSourcesFolderException.java
- src/main/java/net/coru/api/generator/plugin/openapi/exception/OpenApiGeneratedSourceFolderException.java
- src/test/java/net/coru/api/generator/asyncapi/integration/test/AsyncApiGenerationTest.java
- src/test/java/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest.java
- src/test/java/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/api-test.yml
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/IPublishOperation.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/ISubscribeOperation.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/Producer.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/TestApi.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/assets/TestClassName.java
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/event-api.yml
- src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testMultiapiGeneratedSourcesFolder/pom.xml
> Fix adding generated sources to project root

- pom.xml
- src/main/resources/templates/openapi/templateSchema.ftlh
- src/main/resources/templates/openapi/templateSchemaWithLombok.ftlh
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiEnumsGeneration/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testApiEnumsLombokGeneration/assets/ApiTestDTO.java
> Fix missing import for enums

- README.md
- pom.xml
- src/main/java/net/coru/api/generator/plugin/OpenapiMultiFileMojo.java
- src/test/java/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/api-test.yml
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/TestApi.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/pom.xml
> #98 BugFix this for clause

- README.md
- pom.xml
- src/main/java/net/coru/api/generator/plugin/OpenapiMultiFileMojo.java
- src/main/java/net/coru/api/generator/plugin/openapi/model/GlobalObject.java
- src/main/java/net/coru/api/generator/plugin/openapi/template/TemplateFactory.java
- src/main/resources/templates/openapi/templateSchema.ftlh
> 103 scs multiapiopenapi remove useless assignments that are not needed anymore

- README.md
- pom.xml
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/ApiTestInfoDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testOverWriteModelTrue/assets/exception/ModelClassException.java
> Fix OverWriteModel Test

- README.md
- pom.xml
- src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperPathUtil.java
- src/main/java/net/coru/api/generator/plugin/openapi/utils/OpenApiUtil.java
- src/test/java/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testInlineSchemaCreation/api-test.yml
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testInlineSchemaCreation/assets/ApiErrorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testInlineSchemaCreation/assets/ApiTestDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testInlineSchemaCreation/assets/ApiTestProcessorDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testInlineSchemaCreation/assets/ApiTestTypeDTO.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testInlineSchemaCreation/assets/RuleApi.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testInlineSchemaCreation/assets/RulesApi.java
- src/test/resources/net/coru/api/generator/openapi/integration/test/OpenApiGenerationTest/testInlineSchemaCreation/pom.xml
> 126 Fixed minor bug with inlineSchemas

- multiapi-engine/pom.xml
- multiapi-engine/src/main/resources/templates/openapi/templateSchema.ftlh
- multiapi-engine/src/main/resources/templates/openapi/templateSchemaWithLombok.ftlh
- multiapi-engine/src/test/resources/openapigenerator/testMultipleRefGeneration/api-test.yml
- multiapi-engine/src/test/resources/openapigenerator/testMultipleRefGeneration/assets/InlineResponse200CreateGameDTO.java
- multiapi-engine/src/test/resources/openapigenerator/testMultipleRefGeneration/assets/MessageDTO.java
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
I found an issue in your amazing plugin, so I check it and provide a solution. 
Thanks for the work.
> Fix Template Issue

- .github/workflows/maven-central-push.yml
- .github/workflows/maven-pr.yml
- multiapi-engine/pom.xml
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
I have solved multiapi maven plugin missconfig. I also created a new production profile in its pom.xml so it is not necessary to comment gpg sign plugin.
> 149 build error gpg plugin misconfig

- README.md
The version of the plugin remains unchanged as the only file updated is documentation
> #152 changed pom versions to match last version

- multiapi-engine/pom.xml
- multiapi-engine/src/test/java/com/sngular/api/generator/plugin/openapi/OpenApiGeneratorFixtures.java
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
Only changed name in tests to make build work in linux
> fixed wrong name in test for additional properties

- README.md
- multiapi-engine/pom.xml
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/util/MapperUtil.java
- multiapi-engine/src/test/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGeneratorFixtures.java
- multiapi-engine/src/test/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGeneratorTest.java
- multiapi-engine/src/test/resources/asyncapigenerator/testFileGenerationArrayString/assets/IObjectArrayString.java
- multiapi-engine/src/test/resources/asyncapigenerator/testFileGenerationArrayString/assets/ObjectArrayDTO.java
- multiapi-engine/src/test/resources/asyncapigenerator/testFileGenerationArrayString/assets/ObjectArrayMessageDTO.java
- multiapi-engine/src/test/resources/asyncapigenerator/testFileGenerationArrayString/assets/Producer.java
- multiapi-engine/src/test/resources/asyncapigenerator/testFileGenerationArrayString/event-api.yml
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
**Why:** When you include an `array` field in the `yml` file to compound the model object which only have a string type on it, the generation of the model class create the resultant List in a wrong way: `List<string>` instead of `List<String>` 
**Points of Interest:** Added a final modifier where is supposed to be in the `AsyncAPITest` by the `Save Actions Plugin`
> #169 Solve String Problem Error On List

- .github/workflows/update-wiki.yml
> Fixes typo in action update-wiki.yml

- .github/workflows/gradle-portal-push.yml
- .github/workflows/gradle-pr.yml
- .github/workflows/maven-central-push.yml
- .github/workflows/maven-pr.yml
- .github/workflows/pr-review.yml
- scs-multiapi-gradle-plugin/build.gradle
> #210 Fix Gradle version check

- .github/workflows/gradle-portal-push.yml
- .github/workflows/gradle-pr.yml
- .github/workflows/maven-central-push.yml
- .github/workflows/maven-pr.yml
- .github/workflows/pr-review.yml
> #217 Added release-maven and release-gradle labels

- multiapi-engine/pom.xml
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/template/TemplateFactory.java
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/template/TemplateFactory.java
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
Updated swagger core, freemarker, and jackson. Disabled jar minimization. Fixes #228.
> 228 dependency related errors when running the plugin

- multiapi-engine/pom.xml
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperPathUtil.java
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/OpenApiUtil.java
- multiapi-engine/src/test/java/com/sngular/api/generator/plugin/openapi/OpenApiGeneratorFixtures.java
- multiapi-engine/src/test/java/com/sngular/api/generator/plugin/openapi/OpenApiGeneratorTest.java
- multiapi-engine/src/test/resources/openapigenerator/testApiWithNoComponents/api-test.yml
- multiapi-engine/src/test/resources/openapigenerator/testApiWithNoComponents/assets/TestApi.java
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
> NullPointerException when processing a YML with no "components"

- CONTRIBUTING.md
> #236 Update CONTRIBUTING.md

- .github/workflows/gradle-portal-push.yml
- .github/workflows/gradle-pr.yml
- .github/workflows/maven-central-push.yml
- .github/workflows/maven-pr.yml
- .github/workflows/pr-review.yml
- CONTRIBUTING.md
- multiapi-engine/src/test/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGeneratorTest.java
> #241 actions release maven and release gradle act the same way as release

- multiapi-engine/pom.xml
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGenerator.java
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/OpenApiGenerator.java
- multiapi-engine/src/test/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGeneratorFixtures.java
- multiapi-engine/src/test/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGeneratorTest.java
- multiapi-engine/src/test/resources/asyncapigenerator/testNoSchemas/assets/IOnTest.java
- multiapi-engine/src/test/resources/asyncapigenerator/testNoSchemas/assets/IOnTest2.java
- multiapi-engine/src/test/resources/asyncapigenerator/testNoSchemas/assets/Producer.java
- multiapi-engine/src/test/resources/asyncapigenerator/testNoSchemas/assets/TestMsg.java
- multiapi-engine/src/test/resources/asyncapigenerator/testNoSchemas/assets/TestMsgPayload.java
- multiapi-engine/src/test/resources/asyncapigenerator/testNoSchemas/assets/Thing.java
- multiapi-engine/src/test/resources/asyncapigenerator/testNoSchemas/event-api.yml
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
> #238 AsyncAPI generate inlined message schemas

- multiapi-engine/pom.xml
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/util/MapperContentUtil.java
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
asyncapi crash when parsing an array of objects
> 249-asyncapi crash when parsing an array of objects

- multiapi-engine/pom.xml
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGenerator.java
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/util/MapperContentUtil.java
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/util/ReferenceProcessor.java
- multiapi-engine/src/main/java/com/sngular/api/generator/plugin/common/tools/ApiTool.java
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
Added new anti-endless loops controls
> 290 error raised when try to generate an async api model with selfreferences schema objects

- README.md
- multiapi-engine/pom.xml
- multiapi-engine/src/main/resources/templates/asyncapi/templateSchema.ftlh
- multiapi-engine/src/main/resources/templates/asyncapi/templateSchemaWithLombok.ftlh
- multiapi-engine/src/main/resources/templates/openapi/templateEnumSchema.ftlh
- multiapi-engine/src/main/resources/templates/openapi/templateSchema.ftlh
- multiapi-engine/src/main/resources/templates/openapi/templateSchemaWithLombok.ftlh
- scs-multiapi-gradle-plugin/build.gradle
- scs-multiapi-maven-plugin/pom.xml
Fix proposition for issue #319
> Fix variable names - add _ to names starting with a numeric
